version: '3'
services:
  db:
    image: postgres:15.3-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:7.5
    restart: always
    env_file:
      - ./.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

  bot:
    build: .
    command: sh -c "python -m run"
    env_file:
      - ./.env
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  pgadmin-data:
